// @generated
// This file is autogenerated from `routes.json`, do not edit manually.
@live
let makeLink = (~id: string) => {
  `/issue/${id->Js.Global.encodeURIComponent}`
}

@inline
let routePattern = "/issue/:id"

@live
let isRouteActive = ({pathname}: RelayRouter.Bindings.History.location, ~exact: bool=false, ()): bool => {
  RelayRouter.Internal.matchPathWithOptions({"path": routePattern, "end": exact}, pathname)->Belt.Option.isSome
}

@live
let useIsRouteActive = (~exact=false, ()) => {
  let location = RelayRouter.Utils.useLocation()
  React.useMemo2(() => isRouteActive(location, ~exact, ()), (location, exact))
}

@live
type prepareProps = {
  environment: RescriptRelay.Environment.t,
  location: RelayRouter.Bindings.History.location,
  id: string,
}

let makeRouteKey = (
  ~pathParams: Js.Dict.t<string>,
  ~queryParams: RelayRouter.Bindings.QueryParams.t
): string => {
  ignore(queryParams)

  "Root__IssueDetailRoot:"
    ++ pathParams->Js.Dict.get("id")->Belt.Option.getWithDefault("")

}

@live
let makePrepareProps = (. 
  ~environment: RescriptRelay.Environment.t,
  ~pathParams: Js.Dict.t<string>,
  ~queryParams: RelayRouter.Bindings.QueryParams.t,
  ~location: RelayRouter.Bindings.History.location,
): prepareProps => {
  ignore(queryParams)
  {
    environment: environment,

    location: location,
    id: pathParams->Js.Dict.unsafeGet("id"),
  }
}

@live
type renderProps<'prepared> = {
  childRoutes: React.element,
  prepared: 'prepared,
  environment: RescriptRelay.Environment.t,
  location: RelayRouter.Bindings.History.location,
  id: string,
}

@live
type renderers<'prepared> = {
  prepare: prepareProps => 'prepared,
  prepareCode: option<(. prepareProps) => array<RelayRouter.Types.preloadAsset>>,
  render: renderProps<'prepared> => React.element,
}

@obj
external makeRenderer: (
  ~prepare: prepareProps => 'prepared,
  ~prepareCode: prepareProps => array<RelayRouter.Types.preloadAsset>=?,
  ~render: renderProps<'prepared> => React.element,
  unit
) => renderers<'prepared> = ""

