// @generated
// This file is autogenerated, do not edit manually

module Root = {
  module Route = Route__Root_route

  module HomeRoot = {
    module Route = Route__Root__HomeRoot_route

  }
  module IssueDetailRoot = {
    module Route = Route__Root__IssueDetailRoot_route

  }
}